version: '3.3'
services:
    #service 1: definition of mysql database
    rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq  
      restart: always
      ports:
        - "15672:15672"
        - "5672:5672"
    #service 2: definition of your spring-boot app 
    collaboservice:                        #it is just a name, which will be used only in this file.
      image: 619660652947.dkr.ecr.ap-southeast-1.amazonaws.com/collabo-service               #name of the image after dockerfile executes
      container_name: collabo-service-app  #name of the container created from docker image
      build:
        context: .                          #docker file path (. means root directory)
        dockerfile: Dockerfile              #docker file name
      ports:
        - "8096:8096"                       #docker containter port with your os port
      restart: always
      environment:
        - matrix.baseurl=https://matrix.emeritus.org/_matrix/client/v3
        - matrix.username=admin
        - matrix.password=admin@collabo$!12
        - matrix.suffix=:matrix.emeritus.org
        - SPRING_RABBITMQ_HOST=rabbitmq
        - spring.profiles.active=local
        - spring.r2dbc.url=r2dbc:postgresql://localhost:5432/collabo?currentSchema=collabo
        - spring.r2dbc.username=emeritus
        - spring.r2dbc.password=eruditus
        - spring.liquibase.url=jdbc:postgresql://host.docker.internal:5432/collabo?currentSchema=collabo
        - spring.liquibase.user=emeritus
        - spring.liquibase.password=eruditus
      extra_hosts:
        - "localhost:host-gateway"
        - "host.docker.internal:host-gateway"  
      depends_on:                           #define dependencies of this app
        - rabbitmq                          #dependency name (which is defined with this name 'db' in this file earlier)